feat(armv8-a/cpu): Handle unexpected powerdown behavior
bao-project/bao-hypervisor pull request #179
Opened 2024-09-27 14:38 UTC by DavidMCerdeira

We've observed that some platforms behave unexpectedly when performing power down. In these cases, after powerdown, the CPU cores are not awaken by interrupts as expected by Bao. This commit solve this, by adding the ability to skip the powerdown firmware call, instead relying on the fallback mechanism of using wfi.

2024-09-27 14:52 UTC, danielRep approved these changes

2024-09-28 12:09 UTC, josecm commented
@DavidMCerdeira Shouldn't we address other calls to `psci_power_down` such as in `psci_cpu_suspend_handler`

2024-10-01 13:03 UTC, DavidMCerdeira commented
This is a good point
Let me first make a few tests to make sure the PSCI_WAKEUP_IDLE behavior is the same as the PSCI_STATE_TYPE_STANDBY

2024-10-02 14:14 UTC, josecm commented
> This is a good point Let me first make a few tests to make sure the PSCI_WAKEUP_IDLE behavior is the same as the PSCI_STATE_TYPE_STANDBY

Please make sure we are also inline with the PSCI in this respect.

2024-10-02 17:15 UTC, josecm requested changes

2024-10-02 17:15 UTC, josecm commented on src/arch/armv8/armv8-a/psci.c
> +    if (!DEFINED(PLAT_PSCI_STANDBY_NOT_SUPPORTED)) {
Should if be:

```suggestion
    if (DEFINED(PLAT_PSCI_STANDBY_NOT_SUPPORTED)) {
```

2024-10-02 17:15 UTC, josecm commented on src/arch/armv8/armv8-a/psci.c
> +    if (!DEFINED(PLAT_PSCI_POWERDOWN_NOT_SUPPORTED)) {
```suggestion
    if (DEFINED(PLAT_PSCI_POWERDOWN_NOT_SUPPORTED)) {
```

Same as above

2024-10-02 17:15 UTC, josecm commented on src/arch/armv8/psci.c
> +        }
I think we could incorporate this inside the `psci_standby` function itself. Because `wfi`is a legal implementation of that PSCI service.

2024-10-03 08:25 UTC, danielRep approved these changes

2024-10-03 12:50 UTC, josecm approved these changes

2024-10-03 12:50 UTC, danielRep approved these changes

2024-10-03 12:51 UTC, merged