ARMv8 boot: improvement
bao-project/bao-hypervisor pull request #62
Opened 2023-05-07 21:12 UTC by JorgeMVP

Following contributions:
- remove trailling whitespaces
- fix indentation and misspelled comments
- add dsb before sev as required by ARM ARMv8
- use Load-acquire, Store-release to ensure correct sync up at initialization between PEs

Signed-off-by: JorgeMVP <jorgepereira89@gmail.com>

2023-05-07 21:26 UTC, JorgeMVP commented
@josecm In the last commit, I have to confirm something, about the instruction itself.

2023-05-10 23:37 UTC, danielRep commented
Hi @JorgeMVP thanks for the commits! :smiley:  You need to pull your repo to the latest version. Feel free to introduce that changes after the update.

2023-05-11 18:54 UTC, JorgeMVP commented
> Hi @JorgeMVP thanks for the commits! smiley You need to pull your repo to the latest version. Feel free to introduce that changes updating.

Done.

2023-05-11 18:59 UTC, JorgeMVP commented
This is very interesting :) https://developer.arm.com/documentation/den0024/a/Memory-Ordering/Barriers/One-way-barriers

2023-05-12 14:28 UTC, josecm commented
thanks, @JorgeMVP 

It seems we also have the same issue for the 32-bit version of the startup code. Would you be willing to fix it there too? Otherwise, I'll add another commit to the PR.

2023-05-12 23:52 UTC, JorgeMVP commented
> thanks, @JorgeMVP
> 
> It seems we also have the same issue for the 32-bit version of the startup code. Would you be willing to fix it there too? Otherwise, I'll add another commit to the PR.

I can do it, my pleasure ;)

2023-05-15 10:25 UTC, danielRep requested changes
Small format change, than seems perfect to me.

2023-05-15 10:25 UTC, danielRep commented on src/arch/armv8/aarch64/boot.S
> +		add x3, x3, x4
```suggestion
	ldr x4, =(CPU_STACK_OFF + CPU_STACK_SIZE)
	add x3, x3, x4
```

2023-05-15 15:45 UTC, JorgeMVP commented on src/arch/armv8/aarch64/boot.S
> +		add x3, x3, x4
Good catch! I will fix it

2023-05-15 22:50 UTC, AfonsoSantos96 requested changes

2023-05-18 16:38 UTC, JorgeMVP commented on src/arch/armv8/aarch64/boot.S
> +		add x3, x3, x4
fixed. thanks for the review

2023-05-18 16:38 UTC, JorgeMVP commented on src/arch/armv8/aarch32/boot.S
>      ldr r7, =_barrier
Nice suggestion: Fixed. Thanks

2023-05-18 16:39 UTC, JorgeMVP commented on src/arch/armv8/aarch32/boot.S
>      blt 1b
Fixed. Please double check.

2023-05-18 16:39 UTC, JorgeMVP commented on src/arch/armv8/aarch64/boot.S
> +	ldr x4, =_boot_barrier
Fixed. Please double check.

2023-05-22 13:32 UTC, josecm approved these changes

2023-05-22 13:48 UTC, AfonsoSantos96 commented on src/arch/armv8/aarch32/boot.S
>      ldr r7, =_barrier
Looks good to me now, thanks!

2023-05-22 13:49 UTC, AfonsoSantos96 commented on src/arch/armv8/aarch64/boot.S
> +	ldr x4, =_boot_barrier
Looks good to me, thanks!

2023-05-22 13:49 UTC, AfonsoSantos96 approved these changes

2023-05-22 13:51 UTC, AfonsoSantos96 commented on src/arch/armv8/aarch32/boot.S
>      blt 1b
Looks good

2023-05-22 14:02 UTC, merged

2023-05-22 14:02 UTC, josecm commented
Thanks @JorgeMVP !