feat(types): unsigned long width sanity check
bao-project/bao-hypervisor pull request #93
Opened 2023-09-30 19:19 UTC by josecm

2023-10-01 10:11 UTC, sandro2pinto approved these changes
Good to me

2023-10-01 14:05 UTC, danielRep requested changes

2023-10-01 14:05 UTC, danielRep commented on src/core/inc/types.h
> + */
```suggestion
/**
 * We assume LP64 and ILP32 for 64- and 32-bit architectures, respectively, as
 * throughout the code `unsigned long` is the type used for values of the
 * architecture's word width. This is just a sanity check to verify this is the
 * ABI the compiler is effectively using.
 */
```

2023-10-01 19:09 UTC, josecm commented on src/core/inc/types.h
> + */
Typos fixed!

2023-10-01 20:24 UTC, danielRep approved these changes

2023-10-14 15:49 UTC, DavidMCerdeira approved these changes

2023-10-14 17:12 UTC, merged